Repository BlingCorp/bling, pull requests merged in 2021-09, with the labels that each got.

#84 Add a window switcher widget
  AUTHORS.md
  widget/init.lua
  widget/window_switcher.lua
Labels: in review

#109 More scratchpad fixes
  helpers/client.lua
  module/scratchpad.lua
Labels: bug fix

#111 Window switcher docs
  docs/_sidebar.md
  docs/widgets/window_switcher.md
  theme-var-template.lua
Labels: documentation
